# Basics of Numpy  <img src = "numpy1.png">
###### Authored by T.K.Senthil Kumar

#### 1. Create a numpy array with the number of elements equals your age. The value of array elements is a random number between 10 to your age 

In [1]:
#Solution
import numpy as np
ar=np.random.randint(10,24,size=(1,24))
print(np.round(ar,2))

[[22 18 13 18 22 19 15 12 15 15 11 18 22 16 21 22 11 17 21 20 11 20 19 21]]


#### 2. Create a numpy array between 1 to 50 with the span(space) of 2 and print the length of the array

In [2]:
# Solution
a=np.arange(1,51,2)
print(a.astype('int32'))
print(len(a))

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49]
25


#### 3. Create an equally spaced numpy array with 27 elements between 4 and 7 

In [3]:
# Solution
b = np.linspace(4,7,27)
print(b)


[4.         4.11538462 4.23076923 4.34615385 4.46153846 4.57692308
 4.69230769 4.80769231 4.92307692 5.03846154 5.15384615 5.26923077
 5.38461538 5.5        5.61538462 5.73076923 5.84615385 5.96153846
 6.07692308 6.19230769 6.30769231 6.42307692 6.53846154 6.65384615
 6.76923077 6.88461538 7.        ]


#### 4. Create a matrix of size (5 x 4) with random numbers and round off the each elements by only 2 fractional points.

In [4]:
# Solution
c = np.random.rand(5,4)
print(np.round(c,2))

[[0.28 0.4  0.76 0.59]
 [0.91 0.35 0.93 0.85]
 [0.56 0.23 0.14 0.13]
 [0.79 0.43 0.83 0.28]
 [0.67 0.84 0.39 0.8 ]]


#### 5. Create a matrix of size (5x5) with random integers between 5 to 15

In [27]:
# Solution
d = np.random.randint(5,16,size=(5,5))
print(d)



[[10  5 12  9  5]
 [11 14  6  9  5]
 [15 12 12 14  6]
 [ 9  9 15 11  6]
 [12  9 11  5 12]]


#### 6. Create the one dimensional array of zeros of random length below 20 with the data type int32

In [5]:
# Solution
l = np.random.randint(20)
e = np.zeros([1,l],dtype='int')
print(e)
print(type(e))
print(e.dtype)


[[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]]
<class 'numpy.ndarray'>
int32


#### 7. Create a two dimensional array of ones of random row and column lengths with the data type of float32 

In [38]:
# Solution
r = np.random.randint(5)
c = np.random.randint(5)
print(np.ones([r,c],dtype='float32'))

[[1. 1.]
 [1. 1.]
 [1. 1.]]


#### 8. Create a matrix exactly as same as shown below and print its shape, type and dtype
<img src = "np_mat1.png">

In [9]:
# Solution
a = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(a)
print(a.shape)
print(type(a))
print(a.dtype)


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
(5, 5)
<class 'numpy.ndarray'>
int32


#### 9. Access the center pixel of the matrix defined in the question no 8 ( Don't enter the row and column index explicitely)

In [13]:
# Solution
print(a)
print()
print("Central Pixel")
print(a[2,2])



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

Central Pixel
3


#### 10. Print the all the elements of 3rd row of the matrix

In [18]:
# Solution
print(a)
print()
print("All the elements of th first row matrix")
print(a[2,:])



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

All the elements of th first row matrix
[ 5  7  3 76  3]


#### 11. Print the all the elements of 4th columns of the matrix

In [17]:
# Solution
print(a)
print()
print("All the elements of 4th column matrix")
print(a[:,3])



[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

All the elements of 4th column matrix
[34 65 76 54  5]


#### 12. Print the 4 corner pixels of the matrix

In [20]:
# Solution
print(a)
print()
print("All 4 corner pixels")
print(a[[0,4],0:5:4])


[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

All 4 corner pixels
[[ 9 45]
 [23  8]]


#### 13. Create three matrix m1,m2,m3 with the elements grouped in the figure below
<img src = "np_mat2.png">

In [21]:
# Solution 
a = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print("Array=",a)
print()
m1=a[[0,1],2:4]
print("m1=",m1)
print()
m2=a[[3,4],0:2]
print("m2=",m2)
print()
m3=a[2:5, 2:5]
print("m3=",m3)

Array= [[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

m1= [[50 34]
 [34 65]]

m2= [[ 7  8]
 [23 12]]

m3= [[ 3 76  3]
 [ 6 54  6]
 [ 8  5  8]]


#### 14. Reshape all the three matrix segmented in the above task in to three  1-dimensional vector.

In [73]:
# Solution

print(m1.reshape(1,-1))
print(m2.reshape(1,-1))
print(m3.reshape(1,-1))


[[50 34 34 65]]
[[ 7  8 23 12]]
[[ 3 76  3  6 54  6  8  5  8]]


#### 15. Concatenate the matrix m1 and m2 in both vertical and horizontal direction

In [74]:
# Solution

m4=m1+m2
print(m4)


[[57 42]
 [57 77]]


#### 16. Add, Subtract, multiply, divide the matrixes m1 and m2

In [25]:
# Solution
print("Addition=",'\n',np.add(m1,m2))
print()
print("Subtraction=",'\n',np.subtract(m1,m2))
print()
print("Multiplication=",'\n',np.multiply(m1,m2))
print()
print("Division=",'\n',np.divide(m1,m2))



Addition= 
 [[57 42]
 [57 77]]

Subtraction= 
 [[43 26]
 [11 53]]

Multiplication= 
 [[350 272]
 [782 780]]

Division= 
 [[7.14285714 4.25      ]
 [1.47826087 5.41666667]]


#### 17. Add the m1 with m2 by removing the first row and last column of m2

In [26]:
# Solution
a = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(a)
print()
m1=a[0:3,0:3]
print("m1=",m1)
print()
m2=a[2:6,0:3]
print("m2=",m2)
print()
m2[0,:]=m1[0,:]
print('-'*20)
print(m2)
m2[:,2]=m1[:,2]
print('-'*30)
print(m2)

[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]

m1= [[ 9 25 50]
 [ 3 34 34]
 [ 5  7  3]]

m2= [[ 5  7  3]
 [ 7  8  6]
 [23 12  8]]

--------------------
[[ 9 25 50]
 [ 7  8  6]
 [23 12  8]]
------------------------------
[[ 9 25 50]
 [ 7  8 34]
 [23 12 50]]


#### 18. Perform the matrix multiplication between m3 and m4

In [44]:
# Solution
print(np.multiply(m3,m4))


[[  21.         1140.           17.        ]
 [  42.          810.           34.        ]
 [  56.           75.           45.33333333]]


#### 19. Compute the maximum and minimum value of mean, variance, standard deviation for each row of matrix created in question number 8.

In [45]:
# Solution
a = np.array([[9,25,50,34,45],[3,34,34,65,2],[5,7,3,76,3],[7,8,6,54,6],[23,12,8,5,8]])
print(a)
print(np.mean(a))
print(np.var(a))
print(np.std(a))




[[ 9 25 50 34 45]
 [ 3 34 34 65  2]
 [ 5  7  3 76  3]
 [ 7  8  6 54  6]
 [23 12  8  5  8]]
21.28
456.44159999999994
21.364493909287905


#### 20. Compute the average and strike rate for each player and sort it decending way (seperately for avg and strike rate)
<img src = 'crick1.png'>

In [31]:
# Solution 
r=np.array([[54,60,10,65],[102,2,78,32],[3,110,1,92],[56,6,12,42],[12,8,22,11]])
b=np.array([[50,42,22,78],[95,8,65,43],[9,100,7,101],[27,3,11,31],[24,20,36,27]])
print("Runs scored in 4 matches:",r)
print("Balls faced in 4 matches:",b)
# print("Average for MSD:",np.mean(r[0,:]))
# print("Average for KHOLI:",np.mean(r[1,:]))
# print("Average for ROHIT:",np.mean(r[2,:]))
# print("Average for RAHUL:",np.mean(r[3,:]))
# print("Average for DHAWAN:",np.mean(r[4,:]))
a=np.array([])
a=[[np.mean(r[0,:]),np.mean(r[1,:]),np.mean(r[2,:]),np.mean(r[3,:]),np.mean(r[4,:])]] #a=np.mean(r,axis=1)
print(a)
print()
avg=np.sort(a)
print("Average of each player:",np.round(avg,2))
print('-'*50)
print()
s=np.divide(r,b)
print(s)
print()
y=np.array([])
y=[np.sum(s[0,:]),np.sum(s[1,:]),np.sum(s[2,:]),np.sum(s[3,:]),np.sum(s[4,:])]
sr=np.sort(y)                                                        
print("Strike Rate:",np.round(sr,2))                                                      

Runs scored in 4 matches: [[ 54  60  10  65]
 [102   2  78  32]
 [  3 110   1  92]
 [ 56   6  12  42]
 [ 12   8  22  11]]
Balls faced in 4 matches: [[ 50  42  22  78]
 [ 95   8  65  43]
 [  9 100   7 101]
 [ 27   3  11  31]
 [ 24  20  36  27]]
[[47.25, 53.5, 51.5, 29.0, 13.25]]

Average of each player: [[13.25 29.   47.25 51.5  53.5 ]]
--------------------------------------------------

[[1.08       1.42857143 0.45454545 0.83333333]
 [1.07368421 0.25       1.2        0.74418605]
 [0.33333333 1.1        0.14285714 0.91089109]
 [2.07407407 2.         1.09090909 1.35483871]
 [0.5        0.4        0.61111111 0.40740741]]

Strike Rate: [1.92 2.49 3.27 3.8  6.52]


#### 21. The students mark was recorded in a numpy array: marks = np.array([65,84,47,56,89,98,48,77,80,39]).  Cutoff for pass is 50 marks. Write the logic to print the number of students passed and failed. 

In [46]:
# Solution
marks = np.array([65,84,47,56,89,98,48,77,80,39])
index=np.where(marks<50)
print("Failed Students:",len(marks[index]))
print("Passed Students:",len(marks[np.where(marks>=50)]))


Failed Students: 3
Passed Students: 7


#### 22. The class incharge decided to give a mercy mark of 5 for those who scored between 45 and 49. Also the bonus of 5 marks awarded to the students who scored more than 80. Print all the student marks and compute the increase in the pass percentage of class. Any score more than 100 must be recorded as only 100.

In [47]:
# Solution
mar=marks.copy()
mar[np.where((mar>=45) & (mar<50))]= mar[np.where((mar>=45) & (mar<50))] +5
mar[np.where((mar>=80) & (mar<100))]=mar[np.where((mar>=80) & (mar<100))]+5     
print("Actual marks:")
print(marks)
print("Bonus Marks:")
print(mar)


Actual marks:
[65 84 47 56 89 98 48 77 80 39]
Bonus Marks:
[ 65  89  52  56  94 103  53  77  85  39]


#### 23. Print the time taken for performing the following operation using list and numpy array
####       (x(i)^2 +8) / y(i),   where x and y are real integers from 1 to 60000

In [48]:
# Solution
import time
x=range(1,6000)
y=range(1,6000)
a=[]
st=time.time()
print(x)
print(y)

for i,j in zip(x,y):
    a.append((x[i-1]*x[i-1]+8)/y[i-1])

print('Time taken to complete the computation using LIST is : ', (time.time()-st)*1000)

x1=np.arange(1,60000)
y1=np.arange(1,60000)
st1=time.time()
a1=((x1*x1)+8)/y1
print('Time taken to complete the computation using NUMPY ARRAY is : ', (time.time()-st1)*1000)




range(1, 6000)
range(1, 6000)
Time taken to complete the computation using LIST is :  13.987302780151367
Time taken to complete the computation using NUMPY ARRAY is :  0.9984970092773438


In [104]:
# Solution



